name: Flutter CI/CD Pipeline

#on:
#  push:
#    branches:
#      - main  # Runs the workflow on push to the main branch
#  pull_request:
#    branches:
#      - main  # Runs on pull requests to main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Create GitHub Release
    needs: build  # Runs after the build job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag name
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}